fix auto-pr

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -40,39 +40,57 @@ jobs:
             exit 1
           fi
     
-      - name: Crear Auto-PR
-        if: github.event.pull_request.merged == true
-        env:
-          GITHUB_REPOSITORY: ${{ github.repository }}
-          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
-          ORIGEN: ${{ github.event.pull_request.head.ref }}
-          DESTINO: "staging"
-          TOKEN: ${{ secrets.TOKEN }}
-        run: |
-          set -e
+    - name: Crear Auto-PR
+      if: github.event.pull_request.merged == true
+      env:
+        GITHUB_REPOSITORY: ${{ github.ref}}
+        OWNER: ${{ github.actor }}
+        ORIGEN: ${{ github.event.pull_request.head.ref }}
+        DESTINO: "staging"
+        TOKEN: ${{ secrets.TOKEN }}
+      run: |
+        echo -ne "\e[45m[INFO]\e[0m Creando Pull Request para la rama $DESTINO \e[0m\n"
 
-          # Script mejorado
-          echo -ne "\e[45m[INFO]\e[0m Auto-PR CREANDO PULL REQUEST para la rama staging \e[0m\n"
+        PR_RESPONSE=$(curl -s -X POST \
+          -H "Accept: application/vnd.github.v3+json" \
+          -H "Authorization: token $TOKEN" \
+          https://api.github.com/repos/$OWNER/$GITHUB_REPOSITORY/pulls \
+          -d '{
+            "title":"Auto-PR: '${ORIGEN}' -> '${DESTINO}'",
+            "body":"proceso generado por gitbot",
+            "head": "'$ORIGEN'",
+            "base": "'$DESTINO'"
+          }'
+        )
 
-          PR_RESPONSE=$(curl -s -u "${TOKEN}:" -X POST -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls" \
-              -d '{"title":"Auto-PR : '${ORIGEN}' to: '${DESTINO}'","body":"proceso generado por gitbot","head":"'${ORIGEN}'","base":"'${DESTINO}'"}')
+        sleep 3s
 
-          if ! echo "$PR_RESPONSE" | jq empty &> /dev/null; then
-              echo -ne "\e[41m[ERROR]\e[0m La respuesta de GitHub no es un JSON válido.\e[0m\n"
-              exit 1
+        if [[ $(echo "$PR_RESPONSE" | jq -r '.message') == "Validation Failed" ]]; then
+          ERROR_MESSAGE=$(echo "$PR_RESPONSE" | jq -r '.errors[0].message')
+
+          if [[ "$ERROR_MESSAGE" == *"A pull request already exists for"* ]]; then
+
+            EXISTING_PR_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" \
+              "https://api.github.com/repos/$OWNER/$GITHUB_REPOSITORY/pulls?state=open" | jq -r ".[] 
+              | select(.head.ref == \"$ORIGEN\" and .base.ref == \"$DESTINO\") 
+              | .html_url")
+
+              echo -ne "\e[41m[ERROR]\e[0m Ya existe un PR para $ORIGEN -> $DESTINO: $EXISTING_PR_URL\e[0m\n"
           fi
+          exit 1
+        fi
 
-          sleep 5s
+        PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
+        PR_URL=$(echo "$PR_RESPONSE" | jq -r '.html_url')
 
-          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
+        if [[ -z "$PR_NUMBER" ]]; then
+          echo -ne "\e[41m[ERROR]\e[0m Error al crear PR ${DESTINO} -> ${DESTINO}\e[0m\n"
+          echo -ne "\e[41m[ERROR]\e[0m $PR_RESPONSE \e[0m\n"
+          exit 1
+        fi
 
-          if [[ -z "$PR_NUMBER" ]]; then
-              echo -ne "\e[41m[ERROR]\e[0m Error al crear PR para la rama ${DESTINO}\e[0m\n"
-              exit 1
-          fi
-
-          echo -ne "\e[42m[SUCCESS]\e[0m Pull Request creado exitosamente: ${PR_NUMBER}\e[0m\n"
+        echo -ne "\e[42m[SUCCESS]\e[0m Pull Request #${PR_NUMBER} creado exitosamente \e[0m\n"
+        echo -ne "\e[42m[SUCCESS]\e[0m $PR_URL \e[0m\n"
 
       - name: Deploy
         if: github.event_name == 'push'
